### ISSUE TITLE
Button with shadow DOM contents reports "Buttons must have discernible text"

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/sa11y#79]
For a DOM structure like so:

```html
<button>
  <div>
    #shadow-root
      Click me!
  </div>  
</button>
```

The sa11y Jest plugin will report `Buttons must have discernible text`, even though the button has text – it's just in the shadow DOM.

Here is a reduced test case: https://github.com/nolanlawson/sa11y/commit/0825dff4bcc8574681d03e26144e9a1829cf8446

To run it, you can check out the code and then run `npx jest ./packages/assert/`.

<details>
<summary>Full error output</summary>

```
FAIL  packages/assert/__tests__/assert.test.ts
  assertAccessible API
    ✓ should trigger axe runtime exception for non existent rule (8 ms)
    ✕ should throw no errors for dom with no a11y issues with config 0 (130 ms)
    ✕ should throw no errors for dom with no a11y issues with config 1 (69 ms)
    ✕ should use default document, ruleset, formatter when called with no args - expecting 0 assertion (54 ms)
    ✓ should use default document, ruleset, formatter when called with no args - expecting 1 assertion (46 ms)
    ✓ should throw an error with a11y issues found for dom with a11y issues (24 ms)
    ✕ should not throw error with HTML element with no a11y issues (44 ms)
    ✓ should throw error with HTML element with a11y issues (19 ms)
    ✓ should test audio without timing-out using src 0 (4 ms)
    ✓ should test audio without timing-out using src 1 (4 ms)
    ✓ should test audio without timing-out using src 2 (5 ms)
    ✓ should test video without timing-out using src 0 (6 ms)
    ✓ should test video without timing-out using src 1 (7 ms)
    ✓ should test video without timing-out using src 2 (9 ms)

  ● assertAccessible API › should throw no errors for dom with no a11y issues with config 0

    A11yError: 1 Accessibility issues found
     * (button-name) Buttons must have discernible text: #shadow-button
        - Help URL: https://dequeuniversity.com/rules/axe/4.3/button-name

      62 |         }
      63 |         if (a11yResults.length > 0) {
    > 64 |             throw new A11yError(violations, a11yResults, opts);
         |                   ^
      65 |         }
      66 |     }
      67 |

      at Function.checkAndThrow (packages/format/src/format.ts:64:19)
      at assertAccessible (packages/assert/src/assert.ts:44:15)
      at packages/assert/__tests__/assert.test.ts:45:9

  ● assertAccessible API › should throw no errors for dom with no a11y issues with config 1

    A11yError: 1 Accessibility issues found
     * (button-name) Buttons must have discernible text: #shadow-button
        - Help URL: https://dequeuniversity.com/rules/axe/4.3/button-name

      62 |         }
      63 |         if (a11yResults.length > 0) {
    > 64 |             throw new A11yError(violations, a11yResults, opts);
         |                   ^
      65 |         }
      66 |     }
      67 |

      at Function.checkAndThrow (packages/format/src/format.ts:64:19)
      at assertAccessible (packages/assert/src/assert.ts:44:15)
      at packages/assert/__tests__/assert.test.ts:45:9

  ● assertAccessible API › should use default document, ruleset, formatter when called with no args - expecting 0 assertion

    expect(received).resolves.toHaveLength(expected)

    Expected length: 0
    Received length: 1
    Received array:  [{"description": "Ensures buttons have discernible text", "help": "Buttons must have discernible text", "helpUrl": "https://dequeuniversity.com/rules/axe/4.3/button-name?application=axeAPI", "id": "button-name", "impact": "critical", "nodes": [{"all": [], "any": [{"data": null, "id": "button-has-visible-text", "impact": "critical", "message": "Element does not have inner text that is visible to screen readers", "relatedNodes": []}, {"data": null, "id": "aria-label", "impact": "serious", "message": "aria-label attribute does not exist or is empty", "relatedNodes": []}, {"data": null, "id": "aria-labelledby", "impact": "serious", "message": "aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty", "relatedNodes": []}, {"data": {"messageKey": "noAttr"}, "id": "non-empty-title", "impact": "serious", "message": "Element has no title attribute", "relatedNodes": []}, {"data": null, "id": "presentational-role", "impact": "minor", "message": "Element's default semantics were not overridden with role=\"none\" or role=\"presentation\"", "relatedNodes": []}], "html": "<button id=\"shadow-button\"><div id=\"shadow-button-inner\"></div></button>", "impact": "critical", "none": [], "target": ["#shadow-button"]}], "tags": ["cat.name-role-value", "wcag2a", "wcag412", "section508", "section508.22.a", "ACT"]}]

      55 |             document.body.innerHTML = testDOM;
      56 |             expect.assertions(expectedAssertions);
    > 57 |             await expect(getViolationsJSDOM()).resolves.toHaveLength(expectedViolations);
         |                                                         ^
      58 |             await assertAccessible().catch((e) => checkA11yError(e));
      59 |         }
      60 |     );

      at Object.toHaveLength (node_modules/expect/build/index.js:198:20)
      at packages/assert/__tests__/assert.test.ts:57:57

  ● assertAccessible API › should not throw error with HTML element with no a11y issues

    expect(received).toHaveLength(expected)

    Expected length: 0
    Received length: 163
    Received string: "1 Accessibility issues found
     * (button-name) Buttons must have discernible text: #shadow-button
        - Help URL: https://dequeuniversity.com/rules/axe/4.3/button-name"

      58 |     } finally {
      59 |         if (expectNoError) {
    > 60 |             expect(err.message).toHaveLength(0);
         |                                 ^
      61 |         } else if (expectRuntimeError) {
      62 |             expect(err.message).toContain(axeRuntimeExceptionMsgPrefix);
      63 |         } else {

      at checkA11yErrorFunc (packages/test-utils/src/utils.ts:60:33)
      at Object.<anonymous> (packages/assert/__tests__/assert.test.ts:72:9)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 10 passed, 14 total
Snapshots:   3 passed, 3 total
Time:        1.47 s, estimated 2 s
Ran all test suites matching /.\/packages\/assert\//i.
```

</details>

I'm not sure where exactly this is being thrown, because the latest version of the Axe extension does not seem to have this issue:

![Screenshot of Axe DevTools showing only one error about missing video captions](https://user-images.githubusercontent.com/283842/138774022-80aa57d0-d766-46e8-a429-e6646de083ce.png)

**Comment by nolanlawson** [comment]
@mohanraj-r Hey just FYI, we (LWC) are planning to ship a change to synthetic shadow DOM this release (238) which may break for sa11y users due to this issue.

I tried upgrading `axe-core` to the latest (4.3.5) and re-running `yarn test`, but I'm seeing the same test failure in my repro. Maybe the issue is actually in `axe-core`, but somehow the Axe browser extension works around it? Otherwise I'm not sure why this is happening.

**Comment by nolanlawson** [comment]
[I tried to repro](https://bl.ocks.org/nolanlawson/raw/93ece57f90ab9b2318a18628abaac428/) this using vanilla `axe-core`, but it doesn't report any violations for the shadow DOM button. (Check the console.)

When I debug sa11y, though, the violations are coming from this line of code:

https://github.com/salesforce/sa11y/blob/6c900d72c6fad8e5ca94852cf0b2b983939476a6/packages/format/__tests__/format.test.ts#L18

And when I try to debug that, I quickly end up in the guts of `axe-core` itself, where I'm not sure what's going on.

So it seems to have something to do with how sa11y is using `axe-core`, not in `axe-core` itself?

**Comment by nolanlawson** [comment]
Found a reduced repro! It only seems to occur in JSDOM, not Chrome or Firefox or Safari, so I'm guessing this is a JSDOM issue? https://gist.github.com/nolanlawson/726d40e5d4c067b673ca56d438735d7c

**Comment by nolanlawson** [comment]
Never mind, I was using JSDOM incorrectly. It [doesn't repro](https://gist.github.com/nolanlawson/726d40e5d4c067b673ca56d438735d7c) in pure axe-core+jsdom.

I tried downgrading jsdom in that repro from v19 to the version we're using (16.7.0), but it still doesn't repro. So I think it must have something to do with how sa11y is using axe-core, or maybe something jest is doing.

**Comment by nolanlawson** [comment]
OK, I figured out the issue. It's just that inline `<script>`s are not actually evaluated by JSDOM.

In fact, you can remove this `<script>`'s contents entirely and the tests will still pass:

https://github.com/salesforce/sa11y/blob/6c900d72c6fad8e5ca94852cf0b2b983939476a6/packages/test-utils/__data__/noA11yIssues.html#L15-L18

Apologies for my mistake. Looks like there is no issue here.

**Comment by nolanlawson** [comment]
Opened a PR: https://github.com/salesforce/sa11y/pull/89
